package com.cgg.pub.entity;

import java.io.Serializable;
import java.util.Date;

public class OmScriptitem implements Cloneable, Serializable {
    public static final String Table = "t_om_scriptitem";
    public static final String Alias = "as_t_om_scriptitem";
    private static final long serialVersionUID = 1L;
    public static final String DBStrId = "as_t_om_scriptitem.ID";
    public static final String DBStrName = "as_t_om_scriptitem.Name";
    public static final String DBStrTitle = "as_t_om_scriptitem.Title";
    public static final String DBStrScripttypeid = "as_t_om_scriptitem.ScriptTypeId";
    public static final String DBStrActive = "as_t_om_scriptitem.Active";
    public static final String DBStrColorflag = "as_t_om_scriptitem.ColorFlag";
    public static final String DBStrCreatetime = "as_t_om_scriptitem.CreateTime";
    public static final String DBStrCreator = "as_t_om_scriptitem.Creator";
    public static final String DBStrModifytime = "as_t_om_scriptitem.ModifyTime";
    public static final String DBStrModifier = "as_t_om_scriptitem.Modifier";
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column t_om_scriptitem.ID
     * Remark -  *NO SETTING* 
     * DBType - INTEGER
     *
     * @mbggenerated Tue Jun 06 10:37:51 GMT+08:00 2017
     */
    private Integer id;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column t_om_scriptitem.Name
     * Remark - 角标项名称
     * DBType - VARCHAR
     *
     * @mbggenerated Tue Jun 06 10:37:51 GMT+08:00 2017
     */
    private String name;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column t_om_scriptitem.Title
     * Remark - 标题
     * DBType - VARCHAR
     *
     * @mbggenerated Tue Jun 06 10:37:51 GMT+08:00 2017
     */
    private String title;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column t_om_scriptitem.ScriptTypeId
     * Remark - 角标类型ID
     * DBType - INTEGER
     *
     * @mbggenerated Tue Jun 06 10:37:51 GMT+08:00 2017
     */
    private Integer scripttypeid;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column t_om_scriptitem.Active
     * Remark - 是否有效
     * DBType - BIT
     *
     * @mbggenerated Tue Jun 06 10:37:51 GMT+08:00 2017
     */
    private Boolean active;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column t_om_scriptitem.ColorFlag
     * Remark - 颜色标识（1、橙色 2、红色 3、橘黄 4、蓝色 5、绿色 6、蓝色dts）
     * DBType - TINYINT
     *
     * @mbggenerated Tue Jun 06 10:37:51 GMT+08:00 2017
     */
    private Byte colorflag;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column t_om_scriptitem.CreateTime
     * Remark -  *NO SETTING* 
     * DBType - TIMESTAMP
     *
     * @mbggenerated Tue Jun 06 10:37:51 GMT+08:00 2017
     */
    private Date createtime;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column t_om_scriptitem.Creator
     * Remark -  *NO SETTING* 
     * DBType - VARCHAR
     *
     * @mbggenerated Tue Jun 06 10:37:51 GMT+08:00 2017
     */
    private String creator;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column t_om_scriptitem.ModifyTime
     * Remark -  *NO SETTING* 
     * DBType - TIMESTAMP
     *
     * @mbggenerated Tue Jun 06 10:37:51 GMT+08:00 2017
     */
    private Date modifytime;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column t_om_scriptitem.Modifier
     * Remark -  *NO SETTING* 
     * DBType - VARCHAR
     *
     * @mbggenerated Tue Jun 06 10:37:51 GMT+08:00 2017
     */
    private String modifier;

    public OmScriptitem() {
        super();
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    public Integer getScripttypeid() {
        return scripttypeid;
    }

    public void setScripttypeid(Integer scripttypeid) {
        this.scripttypeid = scripttypeid;
    }

    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public Byte getColorflag() {
        return colorflag;
    }

    public void setColorflag(Byte colorflag) {
        this.colorflag = colorflag;
    }

    public Date getCreatetime() {
        return createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    public String getCreator() {
        return creator;
    }

    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    public Date getModifytime() {
        return modifytime;
    }

    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    public String getModifier() {
        return modifier;
    }

    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    public OmScriptitem clone() {
        OmScriptitem o = null;
        try{
            o = (OmScriptitem)super.clone();
        }catch(CloneNotSupportedException ex){
            ex.printStackTrace();
        }
        return o;
    }
}