package com.cgg.pub.entity;

import java.io.Serializable;
import java.util.Date;

public class OmSpecialtopicFilm implements Cloneable, Serializable {
    public static final String Table = "t_om_specialtopic_film";
    public static final String Alias = "as_t_om_specialtopic_film";
    private static final long serialVersionUID = 1L;
    public static final String DBStrId = "as_t_om_specialtopic_film.ID";
    public static final String DBStrAllfilmid = "as_t_om_specialtopic_film.AllFilmId";
    public static final String DBStrSpecialtopicid = "as_t_om_specialtopic_film.SpecialTopicId";
    public static final String DBStrStatus = "as_t_om_specialtopic_film.Status";
    public static final String DBStrSort = "as_t_om_specialtopic_film.Sort";
    public static final String DBStrCreatetime = "as_t_om_specialtopic_film.CreateTime";
    public static final String DBStrCreator = "as_t_om_specialtopic_film.Creator";
    public static final String DBStrModifytime = "as_t_om_specialtopic_film.ModifyTime";
    public static final String DBStrModifier = "as_t_om_specialtopic_film.Modifier";
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column t_om_specialtopic_film.ID
     * Remark -  *NO SETTING* 
     * DBType - INTEGER
     *
     * @mbggenerated Mon Jun 05 13:54:39 GMT+08:00 2017
     */
    private Integer id;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column t_om_specialtopic_film.AllFilmId
     * Remark - 影片ID
     * DBType - INTEGER
     *
     * @mbggenerated Mon Jun 05 13:54:39 GMT+08:00 2017
     */
    private Integer allfilmid;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column t_om_specialtopic_film.SpecialTopicId
     * Remark - 专题ID
     * DBType - INTEGER
     *
     * @mbggenerated Mon Jun 05 13:54:39 GMT+08:00 2017
     */
    private Integer specialtopicid;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column t_om_specialtopic_film.Status
     * Remark - 状态（1有效 0无效）
     * DBType - INTEGER
     *
     * @mbggenerated Mon Jun 05 13:54:39 GMT+08:00 2017
     */
    private Integer status;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column t_om_specialtopic_film.Sort
     * Remark - 排序
     * DBType - INTEGER
     *
     * @mbggenerated Mon Jun 05 13:54:39 GMT+08:00 2017
     */
    private Integer sort;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column t_om_specialtopic_film.CreateTime
     * Remark -  *NO SETTING* 
     * DBType - DATE
     *
     * @mbggenerated Mon Jun 05 13:54:39 GMT+08:00 2017
     */
    private Date createtime;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column t_om_specialtopic_film.Creator
     * Remark -  *NO SETTING* 
     * DBType - VARCHAR
     *
     * @mbggenerated Mon Jun 05 13:54:39 GMT+08:00 2017
     */
    private String creator;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column t_om_specialtopic_film.ModifyTime
     * Remark -  *NO SETTING* 
     * DBType - DATE
     *
     * @mbggenerated Mon Jun 05 13:54:39 GMT+08:00 2017
     */
    private Date modifytime;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column t_om_specialtopic_film.Modifier
     * Remark -  *NO SETTING* 
     * DBType - VARCHAR
     *
     * @mbggenerated Mon Jun 05 13:54:39 GMT+08:00 2017
     */
    private String modifier;

    public OmSpecialtopicFilm() {
        super();
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getAllfilmid() {
        return allfilmid;
    }

    public void setAllfilmid(Integer allfilmid) {
        this.allfilmid = allfilmid;
    }

    public Integer getSpecialtopicid() {
        return specialtopicid;
    }

    public void setSpecialtopicid(Integer specialtopicid) {
        this.specialtopicid = specialtopicid;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getSort() {
        return sort;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }

    public Date getCreatetime() {
        return createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    public String getCreator() {
        return creator;
    }

    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    public Date getModifytime() {
        return modifytime;
    }

    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    public String getModifier() {
        return modifier;
    }

    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    public OmSpecialtopicFilm clone() {
        OmSpecialtopicFilm o = null;
        try{
            o = (OmSpecialtopicFilm)super.clone();
        }catch(CloneNotSupportedException ex){
            ex.printStackTrace();
        }
        return o;
    }
}