package com.cgg.pub.entity;

import java.io.Serializable;
import java.util.Date;

public class OmSpecialtopicPublish implements Cloneable, Serializable {
    public static final String Table = "t_om_specialtopic_publish";
    public static final String Alias = "as_t_om_specialtopic_publish";
    private static final long serialVersionUID = 1L;
    public static final String DBStrId = "as_t_om_specialtopic_publish.ID";
    public static final String DBStrGroupid = "as_t_om_specialtopic_publish.GroupId";
    public static final String DBStrSpecialtopicid = "as_t_om_specialtopic_publish.SpecialTopicId";
    public static final String DBStrIndexstarttime = "as_t_om_specialtopic_publish.IndexStarttime";
    public static final String DBStrIndexendtime = "as_t_om_specialtopic_publish.IndexEndtime";
    public static final String DBStrPaststarttime = "as_t_om_specialtopic_publish.PastStarttime";
    public static final String DBStrPastendtime = "as_t_om_specialtopic_publish.PastEndtime";
    public static final String DBStrPublishposition = "as_t_om_specialtopic_publish.PublishPosition";
    public static final String DBStrStatus = "as_t_om_specialtopic_publish.Status";
    public static final String DBStrSort = "as_t_om_specialtopic_publish.Sort";
    public static final String DBStrCreatetime = "as_t_om_specialtopic_publish.CreateTime";
    public static final String DBStrCreator = "as_t_om_specialtopic_publish.Creator";
    public static final String DBStrModifytime = "as_t_om_specialtopic_publish.ModifyTime";
    public static final String DBStrModifier = "as_t_om_specialtopic_publish.Modifier";
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column t_om_specialtopic_publish.ID
     * Remark -  *NO SETTING* 
     * DBType - INTEGER
     *
     * @mbggenerated Wed May 24 17:19:35 GMT+08:00 2017
     */
    private Integer id;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column t_om_specialtopic_publish.GroupId
     * Remark - 渠道组ID
     * DBType - INTEGER
     *
     * @mbggenerated Wed May 24 17:19:35 GMT+08:00 2017
     */
    private Integer groupid;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column t_om_specialtopic_publish.SpecialTopicId
     * Remark - 专题ID
     * DBType - INTEGER
     *
     * @mbggenerated Wed May 24 17:19:35 GMT+08:00 2017
     */
    private Integer specialtopicid;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column t_om_specialtopic_publish.IndexStarttime
     * Remark - 首页专题上架时间
     * DBType - DATE
     *
     * @mbggenerated Wed May 24 17:19:35 GMT+08:00 2017
     */
    private Date indexstarttime;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column t_om_specialtopic_publish.IndexEndtime
     * Remark - 首页专题下架时间
     * DBType - DATE
     *
     * @mbggenerated Wed May 24 17:19:35 GMT+08:00 2017
     */
    private Date indexendtime;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column t_om_specialtopic_publish.PastStarttime
     * Remark - 往期专题上架时间
     * DBType - DATE
     *
     * @mbggenerated Wed May 24 17:19:35 GMT+08:00 2017
     */
    private Date paststarttime;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column t_om_specialtopic_publish.PastEndtime
     * Remark - 往期专题下架时间
     * DBType - DATE
     *
     * @mbggenerated Wed May 24 17:19:35 GMT+08:00 2017
     */
    private Date pastendtime;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column t_om_specialtopic_publish.PublishPosition
     * Remark - 专题发布位置（1首页专题位  2往期专题位）
     * DBType - INTEGER
     *
     * @mbggenerated Wed May 24 17:19:35 GMT+08:00 2017
     */
    private Integer publishposition;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column t_om_specialtopic_publish.Status
     * Remark - 发布状态（1发布  0未发布）
     * DBType - INTEGER
     *
     * @mbggenerated Wed May 24 17:19:35 GMT+08:00 2017
     */
    private Integer status;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column t_om_specialtopic_publish.Sort
     * Remark - 排序
     * DBType - INTEGER
     *
     * @mbggenerated Wed May 24 17:19:35 GMT+08:00 2017
     */
    private Integer sort;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column t_om_specialtopic_publish.CreateTime
     * Remark -  *NO SETTING* 
     * DBType - DATE
     *
     * @mbggenerated Wed May 24 17:19:35 GMT+08:00 2017
     */
    private Date createtime;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column t_om_specialtopic_publish.Creator
     * Remark -  *NO SETTING* 
     * DBType - VARCHAR
     *
     * @mbggenerated Wed May 24 17:19:35 GMT+08:00 2017
     */
    private String creator;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column t_om_specialtopic_publish.ModifyTime
     * Remark -  *NO SETTING* 
     * DBType - DATE
     *
     * @mbggenerated Wed May 24 17:19:35 GMT+08:00 2017
     */
    private Date modifytime;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column t_om_specialtopic_publish.Modifier
     * Remark -  *NO SETTING* 
     * DBType - VARCHAR
     *
     * @mbggenerated Wed May 24 17:19:35 GMT+08:00 2017
     */
    private String modifier;

    public OmSpecialtopicPublish() {
        super();
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getGroupid() {
        return groupid;
    }

    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    public Integer getSpecialtopicid() {
        return specialtopicid;
    }

    public void setSpecialtopicid(Integer specialtopicid) {
        this.specialtopicid = specialtopicid;
    }

    public Date getIndexstarttime() {
        return indexstarttime;
    }

    public void setIndexstarttime(Date indexstarttime) {
        this.indexstarttime = indexstarttime;
    }

    public Date getIndexendtime() {
        return indexendtime;
    }

    public void setIndexendtime(Date indexendtime) {
        this.indexendtime = indexendtime;
    }

    public Date getPaststarttime() {
        return paststarttime;
    }

    public void setPaststarttime(Date paststarttime) {
        this.paststarttime = paststarttime;
    }

    public Date getPastendtime() {
        return pastendtime;
    }

    public void setPastendtime(Date pastendtime) {
        this.pastendtime = pastendtime;
    }

    public Integer getPublishposition() {
        return publishposition;
    }

    public void setPublishposition(Integer publishposition) {
        this.publishposition = publishposition;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getSort() {
        return sort;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }

    public Date getCreatetime() {
        return createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    public String getCreator() {
        return creator;
    }

    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    public Date getModifytime() {
        return modifytime;
    }

    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    public String getModifier() {
        return modifier;
    }

    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    public OmSpecialtopicPublish clone() {
        OmSpecialtopicPublish o = null;
        try{
            o = (OmSpecialtopicPublish)super.clone();
        }catch(CloneNotSupportedException ex){
            ex.printStackTrace();
        }
        return o;
    }
}